# Atlas/cmake/GenerateUserScripts.cmake

# -----------------------------------------------------------------------
# Runner logic — executed at build time via -P flag
# Variables: SRC_DIR, OUTPUT_FILE, PROJECT_DIR
# -----------------------------------------------------------------------
if(DEFINED SRC_DIR AND DEFINED OUTPUT_FILE)
    file(GLOB_RECURSE HEADER_FILES "${SRC_DIR}/*.h")

    set(SCRIPT_INCLUDES "")
    foreach(HEADER ${HEADER_FILES})
        file(STRINGS "${HEADER}" CONTENTS)
        foreach(LINE ${CONTENTS})
            if(LINE MATCHES "AT_REGISTER_SCRIPT")
                file(RELATIVE_PATH REL_HEADER "${SRC_DIR}" "${HEADER}")
                string(APPEND SCRIPT_INCLUDES "#include \"${REL_HEADER}\"\n")
                if(LINE MATCHES "AT_REGISTER_SCRIPT\\(([A-Za-z_][A-Za-z0-9_]*)\\)")
                    set(CLASS_NAME "${CMAKE_MATCH_1}")
                    list(APPEND SCRIPT_NAMES "${CLASS_NAME}")
                endif()
                break()
            endif()
        endforeach()
    endforeach()

    set(NEW_CONTENTS 
        "// Auto-generated by Atlas — do not edit manually\n#pragma once\n\n${SCRIPT_INCLUDES}")
    
    if(EXISTS "${OUTPUT_FILE}")
        file(READ "${OUTPUT_FILE}" EXISTING_CONTENTS)
        if(NOT EXISTING_CONTENTS STREQUAL NEW_CONTENTS)
            file(WRITE "${OUTPUT_FILE}" "${NEW_CONTENTS}")
            message(STATUS "Atlas: regenerated ${OUTPUT_FILE}")
        endif()
    else()
        file(WRITE "${OUTPUT_FILE}" "${NEW_CONTENTS}")
        message(STATUS "Atlas: regenerated ${OUTPUT_FILE}")
    endif()

    # Always write manifest if PROJECT_DIR provided
    if(DEFINED PROJECT_DIR)
        set(SCRIPT_NAMES_JSON "{\n  \"Scripts\": [")
        set(FIRST TRUE)
        foreach(NAME ${SCRIPT_NAMES})
            if(NOT FIRST)
                string(APPEND SCRIPT_NAMES_JSON ",")
            endif()
            string(APPEND SCRIPT_NAMES_JSON "\n    \"${NAME}\"")
            set(FIRST FALSE)
        endforeach()
        string(APPEND SCRIPT_NAMES_JSON "\n  ]\n}")
        file(WRITE "${PROJECT_DIR}/scripts.manifest" "${SCRIPT_NAMES_JSON}")
    endif()

    return()
endif()

# -----------------------------------------------------------------------
# atlas_generate_script_registry(<target> <src_dir>)
# Called from consumer CMakeLists.txt
# -----------------------------------------------------------------------
function(atlas_generate_script_registry TARGET_NAME SRC_DIR PROJECT_DIR)
    set(OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/generated/UserScripts.h")

    get_filename_component(ATLAS_ROOT "${ATLAS_RESOURCES_DIR}" DIRECTORY)
    set(RUNNER "${ATLAS_ROOT}/cmake/GenerateUserScripts.cmake")

    # Run once at configure time
    execute_process(
        COMMAND ${CMAKE_COMMAND}
            -DSRC_DIR=${SRC_DIR}
            -DOUTPUT_FILE=${OUTPUT_FILE}
            -DPROJECT_DIR=${PROJECT_DIR}
            -P ${RUNNER}
    )

    # Run at every build
    add_custom_command(TARGET ${TARGET_NAME} PRE_BUILD
        COMMAND ${CMAKE_COMMAND}
            -DSRC_DIR=${SRC_DIR}
            -DOUTPUT_FILE=${OUTPUT_FILE}
            -DPROJECT_DIR=${PROJECT_DIR}
            -P ${RUNNER}
        COMMENT "Scanning for Atlas scripts in ${SRC_DIR}"
    )

    target_include_directories(${TARGET_NAME} PRIVATE
        "${CMAKE_CURRENT_BINARY_DIR}/generated"
        "${SRC_DIR}"
    )
endfunction()